DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
  password TEXT NOT NULL,
  created_date TEXT NOT NULL
);

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_user INTEGER REFERENCES users(id),
	title TEXT NOT NULL,
	content TEXT NOT NULL,
  created_date TEXT NOT NULL,
	edited_date TEXT DEFAULT null
);

SELECT * FROM users;

SELECT * FROM posts;
